Adding startup probe for kube-mgmt container
open-policy-agent/kube-mgmt pull request #215
Opened 2023-06-10 12:19 UTC by saranyareddy24

Fix for #210

Fix provided:

Before starting kube-mgmt container, the startup probe will check the health of OPA container using the API <http-scheme>://127.0.0.1:<opa-port>/health 

kubectl describe pod:
```
 Startup:        http-get https://:8181/health delay=20s timeout=1s period=10s #success=1 #failure=5
```
Pod came up successfully with the change
```
kc get pods
NAME                                 READY   STATUS    RESTARTS   AGE
opa-opa-kube-mgmt-66ff988f55-5wdjv   2/2     Running   0          32s
```

2023-06-10 13:24 UTC, eshepelyuk requested changes
1. linter tests should be added since new value(s) are added.
1. e2e test should be provided.
1. For configuration flexibility - this startup check should be completely picked up from values, i.e. be configurable.

2023-06-10 13:24 UTC, eshepelyuk commented on charts/opa-kube-mgmt/templates/deployment.yaml
> +              path: /health
It's mentioned in the description - the URL should be configurable.

2023-06-10 13:35 UTC, eshepelyuk commented
@saranyareddy24 

please use this conventions to link a PR to an issue

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2023-06-10 13:49 UTC, saranyareddy24 commented
I am not able to link the PR to the issue now, doubting if I don't have permissions for it.

2023-06-10 13:50 UTC, eshepelyuk commented
> I am not able to link the PR to the issue now, doubting if I don't have permissions for it.

just read carefully the link I've provided.

2023-06-10 14:27 UTC, saranyareddy24 commented
Linter test for helm

./test/linter/test.sh
==> Linting charts/opa-kube-mgmt

1 chart(s) linted, 0 chart(s) failed
==> Linting charts/opa-kube-mgmt

1 chart(s) linted, 0 chart(s) failed
==> Linting charts/opa-kube-mgmt

1 chart(s) linted, 0 chart(s) failed
engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
==> Linting charts/opa-kube-mgmt

1 chart(s) linted, 0 chart(s) failed
==> Linting charts/opa-kube-mgmt

1 chart(s) linted, 0 chart(s) failed
==> Linting charts/opa-kube-mgmt

1 chart(s) linted, 0 chart(s) failed
==> Linting charts/opa-kube-mgmt

1 chart(s) linted, 0 chart(s) failed
==> Linting charts/opa-kube-mgmt

1 chart(s) linted, 0 chart(s) failed
==> Linting charts/opa-kube-mgmt

1 chart(s) linted, 0 chart(s) failed
==> Linting charts/opa-kube-mgmt

1 chart(s) linted, 0 chart(s) failed
==> Linting charts/opa-kube-mgmt

1 chart(s) linted, 0 chart(s) failed
==================================================================================
                                LINT PASSED
==================================================================================

2023-06-10 14:29 UTC, eshepelyuk commented
> Linter test for helm
> 
> ./test/linter/test.sh
> ==> Linting charts/opa-kube-mgmt
> 
> 1 chart(s) linted, 0 chart(s) failed
> ==> Linting charts/opa-kube-mgmt
> 
> 1 chart(s) linted, 0 chart(s) failed
> ==> Linting charts/opa-kube-mgmt
> 
> 1 chart(s) linted, 0 chart(s) failed
> engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
> engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
> engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
> engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
> engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
> engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
> engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
> engine.go:189: [INFO] Fail: cert-manager CRD does not appear to be installed
> ==> Linting charts/opa-kube-mgmt
> 
> 1 chart(s) linted, 0 chart(s) failed
> ==> Linting charts/opa-kube-mgmt
> 
> 1 chart(s) linted, 0 chart(s) failed
> ==> Linting charts/opa-kube-mgmt
> 
> 1 chart(s) linted, 0 chart(s) failed
> ==> Linting charts/opa-kube-mgmt
> 
> 1 chart(s) linted, 0 chart(s) failed
> ==> Linting charts/opa-kube-mgmt
> 
> 1 chart(s) linted, 0 chart(s) failed
> ==> Linting charts/opa-kube-mgmt
> 
> 1 chart(s) linted, 0 chart(s) failed
> ==> Linting charts/opa-kube-mgmt
> 
> 1 chart(s) linted, 0 chart(s) failed
> ==> Linting charts/opa-kube-mgmt
> 
> 1 chart(s) linted, 0 chart(s) failed
> 
> ==================================================================================
>                                 LINT PASSED
> ==================================================================================
> 

why did you post it here ??

2023-06-12 16:01 UTC, ievgenii-shepeliuk commented on charts/opa-kube-mgmt/templates/deployment.yaml
> +{{ toYaml .Values.mgmt.startupProbe | indent 12 }}
It's better to use `nindent`, so you can align this block properly with `startupProbe`.

2023-06-13 09:28 UTC, saranyareddy24 commented
> 1. For configuration flexibility - this startup probe should be completely picked up from values, i.e. be configurable.
> 2. linter tests should be added since new value(s) are added.
> 3. new e2e test should be provided, to check kube mgmt is not starting in case opa is down.

Existing helm linter tests will cover the new values as well.

2023-06-13 09:38 UTC, saranyareddy24 commented
@eshepelyuk Is there a way to get more logs on the build failure to identify why the build is failing?

2023-06-13 13:47 UTC, eshepelyuk commented
> @eshepelyuk Is there a way to get more logs on the build failure to identify why the build is failing?

I don't know TBH. But is it passing OK locally for you ?

2023-06-13 13:51 UTC, anderseknert commented
@saranyareddy24 logs are over here: https://github.com/open-policy-agent/kube-mgmt/actions/runs/5253679992/jobs/9491313262

This looks relevant:
```
Starting deploy...
Helm release kube-mgmt not installed. Installing...
Error: INSTALLATION FAILED: context deadline exceeded
deploying "kube-mgmt": install: exit status 1
error: Recipe `up` failed on line 63 with exit code 1
```

2023-06-13 15:51 UTC, saranyareddy24 commented
> @saranyareddy24 logs are over here: https://github.com/open-policy-agent/kube-mgmt/actions/runs/5253679992/jobs/9491313262
> 
> This looks relevant:
> 
> ```
> Starting deploy...
> Helm release kube-mgmt not installed. Installing...
> Error: INSTALLATION FAILED: context deadline exceeded
> deploying "kube-mgmt": install: exit status 1
> error: Recipe `up` failed on line 63 with exit code 1
> ```

I went through this, I wanted to see kubectl describe pod to see why it is crashing, but I noticed that those lines were commented in build file.

2023-06-13 16:22 UTC, saranyareddy24 commented
> > @eshepelyuk Is there a way to get more logs on the build failure to identify why the build is failing?
> 
> I don't know TBH. But is it passing OK locally for you ?

I ran it locally and found that, it is failing at startup probe.
```
Startup probe failed: Get "https://10.244.0.36:8181/health": http: server gave HTTP response to HTTPS client.
```
Will fix it.

2023-06-13 17:05 UTC, merged