Add template for ServiceAccount annotations
open-policy-agent/kube-mgmt pull request #239
Opened 2023-11-01 18:31 UTC by crdueck

ServiceAccount annotations are needed to support web identity credentials: https://www.openpolicyagent.org/docs/latest/management-bundles/#web-identity-credentials

2023-11-01 18:39 UTC, eshepelyuk requested changes
Hello

1. values schema should be adjusted and corresponding lint test cases added into `test/lint`.
1. helm unit tests should be added for affected template in `test/unit`.

2023-11-02 17:22 UTC, crdueck commented
I added a simple unit test for the serviceaccount annotations, but I'm less sure what to do about the values schema and linting you asked for. 

The only example of schema & linting I found was for the `image` field, which makes sense because it has required sub-fields `image.{repository,tag}`. Whereas annotations aren't required and can have arbitrary sub-fields. My motivating use case just happens to be the IRSA role annotation.

So, could you help me better understand what you would want to see for annotations schema and linting?

2023-11-02 17:28 UTC, eshepelyuk commented
> I added a simple unit test for the serviceaccount annotations, but I'm less sure what to do about the values schema and linting you asked for. 
> 
> The only example of schema & linting I found was for the `image` field, which makes sense because it has required sub-fields `image.{repository,tag}`. Whereas annotations aren't required and can have arbitrary sub-fields. My motivating use case just happens to be the IRSA role annotation.
> 
> So, could you help me better understand what you would want to see for annotations schema and linting?

Hello

1. schema must reflect\describe entire structure of values.yaml. It was recently introduced, so it's kinda empty, but it's assumed it will be improved with time.
1. annotations are not arbitrary values, it is dictionary of string to string and this can be described via json schema. Also in schema one can point that service account annotation by default is an empty dictionary.

2023-11-02 17:35 UTC, eshepelyuk requested changes
Don't forget to rebase and squash a PR into a single commit.

2023-11-02 17:35 UTC, eshepelyuk commented on test/unit/sa_annotations_test.yaml
plz name it `sa_test.yaml`

2023-11-03 16:41 UTC, crdueck commented
I added a schema for the `serviceAccount` values and a lint check for the annotations. Rebased and squashed as well

2023-11-03 16:46 UTC, eshepelyuk approved these changes

2023-11-03 16:49 UTC, merged

2023-11-03 16:50 UTC, eshepelyuk commented
Thanks for the contribution
Will be abailable in 8.5.3

https://github.com/open-policy-agent/kube-mgmt/actions/runs/6748036699