Dependencies/Fix High Severity Vulnerability `CVE-2023-44487` Found in the latest image `8.5.11`
open-policy-agent/kube-mgmt pull request #271
Opened 2024-12-09 00:30 UTC by mlajkim

# Issue
![image](https://github.com/user-attachments/assets/0584cc38-210e-4b03-97e1-232e52b64756)
https://github.com/open-policy-agent/kube-mgmt/issues/270

## What's done
🟡 TODO

2024-12-09 03:18 UTC, mlajkim commented
- [ ] Use the `go 1.24` as `go 1.23` may have the following: `fatal error: to many concurrent timer firings`

2024-12-11 02:26 UTC, mlajkim commented
@eshepelyuk 
We've found a vulnerability in the package and have fixed it in this PR. Could you please review it for us? Thank you.

2024-12-11 07:26 UTC, eshepelyuk requested changes
PR should be rebased into single commit. otherwise LGTM.

2024-12-12 00:13 UTC, mlajkim commented
> PR should be rebased into single commit. otherwise LGTM.

@eshepelyuk 
Take a look if it is handled! Thanks.

2024-12-12 00:26 UTC, eshepelyuk commented
> > PR should be rebased into single commit. otherwise LGTM.
> 
> @eshepelyuk 
> Take a look if it is handled! Thanks.

yes, but leave proper commit message.
`fix vul` is not acceptable.

2024-12-12 00:58 UTC, mlajkim commented
@eshepelyuk take a look once again.

2024-12-12 01:45 UTC, merged

2024-12-12 01:47 UTC, eshepelyuk commented
Thanks
will be available in https://github.com/open-policy-agent/kube-mgmt/releases/tag/8.5.12